// <auto-generated />
using System;
using IECE_WebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IECE_WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210311032503_UsuarioMigration")]
    partial class UsuarioMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //modelBuilder.Entity("IECE_WebApi.Models.Distrito", b =>
            //    {
            //        b.Property<int>("dis_Id_Distrito")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<bool>("dis_Activo");

            //        b.Property<string>("dis_Alias");

            //        b.Property<string>("dis_Area");

            //        b.Property<string>("dis_Domicilio_Especial_Correspondencia");

            //        b.Property<DateTime>("dis_Fecha_Cambio_Obispo");

            //        b.Property<DateTime>("dis_Fecha_Organizacion");

            //        b.Property<DateTime>("dis_Fecha_Ultimo_Cambio_Admon");

            //        b.Property<int>("dis_Numero");

            //        b.Property<string>("dis_Tipo_Distrito");

            //        b.Property<int>("pem_Id_Obispo");

            //        b.Property<int>("pem_Id_Obispo_Suplente");

            //        b.Property<int>("pem_Id_Secretario");

            //        b.Property<int>("pem_Id_Sub_Secretario");

            //        b.Property<int>("pem_Id_Sub_Tesorero");

            //        b.Property<int>("pem_Id_Tesorero");

            //        b.Property<int>("sec_Id_Sector_Base");

            //        b.HasKey("dis_Id_Distrito");

            //        b.ToTable("Distrito");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.Estado", b =>
            //    {
            //        b.Property<int>("est_Id_Estado")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<string>("est_Nombre");

            //        b.Property<string>("est_Nombre_Corto");

            //        b.Property<string>("est_Pais");

            //        b.Property<int>("pais_Id_Pais");

            //        b.HasKey("est_Id_Estado");

            //        b.ToTable("Estado");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.HogarDomicilio", b =>
            //    {
            //        b.Property<int>("hd_Id_Hogar")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<DateTime>("Fecha_Registro");

            //        b.Property<int>("est_Id_Estado");

            //        b.Property<string>("hd_Calle");

            //        b.Property<string>("hd_Localidad");

            //        b.Property<string>("hd_Municipio_Ciudad");

            //        b.Property<string>("hd_Numero_Exterior");

            //        b.Property<string>("hd_Numero_Interior");

            //        b.Property<string>("hd_Subdivision");

            //        b.Property<string>("hd_Telefono");

            //        b.Property<string>("hd_Tipo_Subdivision");

            //        b.Property<int>("pais_Id_Pais");

            //        b.Property<int>("usu_Id_Usuario");

            //        b.HasKey("hd_Id_Hogar");

            //        b.ToTable("HogarDomicilio");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.Hogar_Persona", b =>
            //    {
            //        b.Property<int>("hp_Id_Hogar_Persona")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<DateTime>("Fecha_Registro");

            //        b.Property<int>("hd_Id_Hogar");

            //        b.Property<int>("hp_Jerarquia");

            //        b.Property<int>("per_Id_Persona");

            //        b.Property<int>("usu_Id_Usuario");

            //        b.HasKey("hp_Id_Hogar_Persona");

            //        b.ToTable("Hogar_Persona");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.Pais", b =>
            //    {
            //        b.Property<int>("pais_Id_Pais")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<string>("pais_Nombre");

            //        b.Property<string>("pais_Nombre_Corto");

            //        b.HasKey("pais_Id_Pais");

            //        b.ToTable("Pais");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.Persona", b =>
            //    {
            //        b.Property<int>("per_Id_Persona")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<DateTime>("Fecha_Registro");

            //        b.Property<bool>("per_Activo");

            //        b.Property<string>("per_Apellido_Materno")
            //            .IsRequired();

            //        b.Property<string>("per_Apellido_Paterno")
            //            .IsRequired();

            //        b.Property<string>("per_Bajo_Imposicion_De_Manos");

            //        b.Property<bool>("per_Bautizado");

            //        b.Property<string>("per_Cambios_De_Domicilio");

            //        b.Property<int>("per_Cantidad_Hijos");

            //        b.Property<string>("per_Cargos_Desempenados");

            //        b.Property<string>("per_Categoria")
            //            .IsRequired();

            //        b.Property<string>("per_Email_Personal");

            //        b.Property<bool>("per_En_Comunion");

            //        b.Property<string>("per_Estado_Civil");

            //        b.Property<DateTime>("per_Fecha_Bautismo");

            //        b.Property<DateTime>("per_Fecha_Boda_Civil");

            //        b.Property<DateTime>("per_Fecha_Boda_Eclesiastica");

            //        b.Property<DateTime>("per_Fecha_Nacimiento");

            //        b.Property<DateTime>("per_Fecha_Recibio_Espiritu_Santo");

            //        b.Property<string>("per_Libro_Acta_Boda_Civil");

            //        b.Property<string>("per_Lugar_Bautismo");

            //        b.Property<string>("per_Lugar_Boda_Eclesiastica");

            //        b.Property<string>("per_Lugar_De_Nacimiento");

            //        b.Property<string>("per_Ministro_Que_Bautizo");

            //        b.Property<string>("per_Nacionalidad");

            //        b.Property<string>("per_Nombre")
            //            .IsRequired();

            //        b.Property<string>("per_Nombre_Abuela_Materna");

            //        b.Property<string>("per_Nombre_Abuela_Paterna");

            //        b.Property<string>("per_Nombre_Abuelo_Materno");

            //        b.Property<string>("per_Nombre_Abuelo_Paterno");

            //        b.Property<string>("per_Nombre_Conyuge");

            //        b.Property<string>("per_Nombre_Hijos");

            //        b.Property<string>("per_Nombre_Madre");

            //        b.Property<string>("per_Nombre_Padre");

            //        b.Property<string>("per_Num_Acta_Boda_Civil");

            //        b.Property<string>("per_Oficialia_Boda_Civil");

            //        b.Property<string>("per_RFC_Sin_Homo")
            //            .IsRequired();

            //        b.Property<string>("per_Registro_Civil");

            //        b.Property<string>("per_Telefono_Movil");

            //        b.Property<bool>("per_Visibilidad_Abierta");

            //        b.Property<bool>("per_Vivo");

            //        b.Property<string>("per_foto");

            //        b.Property<int>("pro_Id_Profesion_Oficio1");

            //        b.Property<int>("pro_Id_Profesion_Oficio2");

            //        b.Property<int>("sec_Id_Sector");

            //        b.Property<int>("usu_Id_Usuario");

            //        b.HasKey("per_Id_Persona");

            //        b.ToTable("Persona");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.PersonaDomicilio", b =>
            //    {
            //        b.Property<int>("id")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<int?>("HogarDomicilioEntityhd_Id_Hogar");

            //        b.Property<int?>("PersonaEntityper_Id_Persona");

            //        b.HasKey("id");

            //        b.HasIndex("HogarDomicilioEntityhd_Id_Hogar");

            //        b.HasIndex("PersonaEntityper_Id_Persona");

            //        b.ToTable("PersonaDomicilio");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.Profesion_Oficio", b =>
            //    {
            //        b.Property<int>("pro_Id_Profesion_Oficio")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<DateTime>("Fecha_Registro");

            //        b.Property<string>("pro_Categoria")
            //            .IsRequired();

            //        b.Property<string>("pro_Sub_Categoria")
            //            .IsRequired();

            //        b.Property<int>("usu_Id_Usuario");

            //        b.HasKey("pro_Id_Profesion_Oficio");

            //        b.ToTable("Profesion_Oficio");
            //    });

            //modelBuilder.Entity("IECE_WebApi.Models.Sector", b =>
            //    {
            //        b.Property<int>("sec_Id_Sector")
            //            .ValueGeneratedOnAdd()
            //            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            //        b.Property<DateTime>("Fecha_Registro");

            //        b.Property<int>("dis_Id_Distrito");

            //        b.Property<int>("pem_Id_Pastor");

            //        b.Property<int>("pem_Id_Secretario");

            //        b.Property<int>("pem_Id_Tesorero");

            //        b.Property<bool>("sec_Activo");

            //        b.Property<string>("sec_Alias");

            //        b.Property<DateTime>("sec_Fecha_Inicio_Pastorado_Actual");

            //        b.Property<DateTime>("sec_Fecha_Organizacion");

            //        b.Property<int>("sec_Membresia");

            //        b.Property<int>("sec_Numero");

            //        b.Property<string>("sec_Tipo_Sector");

            //        b.Property<int>("usu_Id_Usuario");

            //        b.HasKey("sec_Id_Sector");

            //        b.ToTable("Sector");
            //    });

            modelBuilder.Entity("IECE_WebApi.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            //modelBuilder.Entity("IECE_WebApi.Models.PersonaDomicilio", b =>
            //    {
            //        b.HasOne("IECE_WebApi.Models.HogarDomicilio", "HogarDomicilioEntity")
            //            .WithMany()
            //            .HasForeignKey("HogarDomicilioEntityhd_Id_Hogar");

            //        b.HasOne("IECE_WebApi.Models.Persona", "PersonaEntity")
            //            .WithMany()
            //            .HasForeignKey("PersonaEntityper_Id_Persona");
            //    });
#pragma warning restore 612, 618
        }
    }
}
